workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    cache:
      cache_paths:
        - ~/Library/Caches/org.swift.swiftpm
        - ~/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Run Tests
        script: |
          xcodebuild clean test \
            -project game-catalogue-uikit.xcodeproj \
            -scheme game-catalogue-uikit \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Build App
        script: |
          xcodebuild clean build \
             -project game-catalogue-uikit.xcodeproj \
             -scheme game-catalogue-uikit \
              -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
